version: '3.0'
services:
  frontend:
    image: 'nikhilmohandas/frontend:latest'
    ports:
      - '4200:4200'
    container_name: 'frontend'
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - backend

  backend:
    image: 'nikhilmohandas/backend:latest'
    ports:
      - '8080:8080'
    container_name: 'backend'
    environment:
      - SERVER_PORT=8080
      - MONGO_URI=mongodb://host.docker.internal:27017/urlShortner
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - database

  database:
    image: 'mongo'
    container_name: 'database'
    ports:
      - "27017:27017"
